# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShortestPath
                                 A QGIS plugin
 Find the shortest route betwen nodes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-09-13
        copyright            : (C) 2024 by Carlos Pimentel / Freelancer
        email                : costa.pimentel@ubi.pt
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Carlos Pimentel / Freelancer'
__date__ = '2024-09-13'
__copyright__ = '(C) 2024 by Carlos Pimentel / Freelancer'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShortestPath class from file ShortestPath.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shortest_path import ShortestPathPlugin
    return ShortestPathPlugin()
